WebUI/Areas/Admin/Models/RoleViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebUI.Areas.Admin.Models
{
    public class RoleViewModel
    {
        public string Name { get; set; }
        public string Id { get; set; }
    }
}

WebUI/Areas/Admin/Controllers/PermissionController.cs
using AdminPanel.Application.Constants;
using Infrastructure.Identity.Models;
using AdminPanel.Web.Abstractions;
using WebUI.Areas.Admin.Models;
using AdminPanel.WebUI.Helpers;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Application.Features.Logs.Commands;
using AdminPanel.Infrastructure.AuditModels;
using Newtonsoft.Json;

namespace WebUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "SuperAdmin")]
    public class PermissionController : BaseController<PermissionController>
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        public PermissionController(RoleManager<IdentityRole> roleManager, UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        public async Task<ActionResult> Index(string roleId)
        {
            var model = new PermissionViewModel();
            var allPermissions = new List<RoleClaimsViewModel>();
            allPermissions.GetPermissions(typeof(Permissions.Communities), roleId);
            allPermissions.GetPermissions(typeof(Permissions.Users), roleId);
            var role = await _roleManager.FindByIdAsync(roleId);
            model.RoleId = roleId;
            var claims = await _roleManager.GetClaimsAsync(role);
            var claimsModel = _mapper.Map<List<RoleClaimsViewModel>>(claims);
            var allClaimValues = allPermissions.Select(a => a.Value).ToList();
            var roleClaimValues = claimsModel.Select(a => a.Value).ToList();
            var authorizedClaims = allClaimValues.Intersect(roleClaimValues).ToList();
            foreach (var permission in allPermissions)
            {
                if (authorizedClaims.Any(a => a == permission.Value))
                {
                    permission.Selected = true;
                }
            }
            model.RoleClaims = _mapper.Map<List<RoleClaimsViewModel>>(allPermissions);
            ViewData["Title"] = $"Права для {role.Name}";
            ViewData["Caption"] = $"Керувати правами для {role.Name}.";
            return View(model);
        }

        public async Task<IActionResult> Update(PermissionViewModel model)
        {
            var role = await _roleManager.FindByIdAsync(model.RoleId);
            //Remove all Claims First
            var claims = await _roleManager.GetClaimsAsync(role);
            foreach (var claim in claims)
            {
                await _roleManager.RemoveClaimAsync(role, claim);
            }
            var selectedClaims = model.RoleClaims.Where(a => a.Selected).ToList();
            foreach (var claim in selectedClaims)
            {
                await _roleManager.AddPermissionClaim(role, claim.Value);
            }

            _notify.Error($"Дозволи для ролі {role.Name} змінено");

            return RedirectToAction("Index", new { roleId = model.RoleId });
        }
    }
}

WebUI/Areas/Admin/Controllers/RoleController.cs
using AdminPanel.Application.Enums;
using AdminPanel.Infrastructure.AuditModels;
using Infrastructure.Identity.Models;
using AdminPanel.Web.Abstractions;
using Application.Features.Logs.Commands;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using WebUI.Areas.Admin.Models;

namespace WebUI.Areas.Admin
{
    [Area("Admin")]
    [Authorize(Roles = "SuperAdmin")]
    public class RoleController : BaseController<RoleController>
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<ApplicationUser> _userManager;

        public RoleController(UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> LoadAll()
        {
            var roles = await _roleManager.Roles.ToListAsync();
            var model = _mapper.Map<IEnumerable<RoleViewModel>>(roles);
            
            return PartialView("_ViewAll", model);
        }

        public async Task<IActionResult> OnGetCreate(string id)
        {
            if (string.IsNullOrEmpty(id))
                return new JsonResult(new { isValid = true, html = await _viewRenderer.RenderViewToStringAsync("_Create", new RoleViewModel()) });
            else
            {
                var role = await _roleManager.FindByIdAsync(id);
                var roleviewModel = _mapper.Map<RoleViewModel>(role);
                
                return new JsonResult(new { isValid = true, html = await _viewRenderer.RenderViewToStringAsync("_Create", roleviewModel) });
            }
        }

        [HttpPost]
        public async Task<IActionResult> OnPostCreate(RoleViewModel role)
        {
            if (ModelState.IsValid)
            {
                var result = await _roleManager.FindByNameAsync(role.Name);

                if (result == null)
                {
                    if (string.IsNullOrEmpty(role.Id))
                    {
                        _notify.Success($"Роль {role.Name} створено");
                        await _roleManager.CreateAsync(new IdentityRole(role.Name));

                        Log log = new Log()
                        {
                            UserId = _userService.UserId,
                            Action = "Create",
                            TableName = "Roles",
                            NewValues = role
                        };

                        await _mediator.Send(new AddLogCommand() { Log = log });
                    }
                    else
                    {
                        var existingRole = await _roleManager.FindByIdAsync(role.Id);

                        Log log = new Log()
                        {
                            UserId = _userService.UserId,
                            Action = "Update",
                            TableName = "Roles",
                            OldValues = _mapper.Map<RoleViewModel>(existingRole),
                            NewValues = role
                        };

                        existingRole.Name = role.Name;
                        existingRole.NormalizedName = role.Name.ToUpper();
                        await _roleManager.UpdateAsync(existingRole);

                        _notify.Success($"Роль {role.Name} змінено");
                        await _mediator.Send(new AddLogCommand() { Log = log });
                    }
                }
                else
                {
                    _notify.Error($"Роль {role.Name} вже існує");
                }

                var roles = await _roleManager.Roles.ToListAsync();
                var mappedRoles = _mapper.Map<IEnumerable<RoleViewModel>>(roles);
                var html = await _viewRenderer.RenderViewToStringAsync("_ViewAll", mappedRoles);
                
                return new JsonResult(new { isValid = true, html = html });
            }
            else 
            {
               var html = await _viewRenderer.RenderViewToStringAsync<RoleViewModel>("_CreateOrEdit", role);
               return new JsonResult(new { isValid = false, html = html });
            }
        }

        public async Task<JsonResult> OnPostDelete(string id)
        {
            var existingRole = await _roleManager.FindByIdAsync(id);
            
            if (existingRole.Name != Roles.SuperAdmin.ToString())
            {
                bool roleIsNotUsed = true;
                var allUsers = await _userManager.Users.ToListAsync();
                
                foreach (var user in allUsers)
                    if (await _userManager.IsInRoleAsync(user, existingRole.Name))
                        roleIsNotUsed = false;

                if (roleIsNotUsed)
                {
                    await _roleManager.DeleteAsync(existingRole);

                    Log log = new Log()
                    {
                        UserId = _userService.UserId,
                        Action = "Delete",
                        TableName = "Roles",
                        OldValues = _mapper.Map<RoleViewModel>(existingRole)
                    };

                    await _mediator.Send(new AddLogCommand() { Log = log });
                    _notify.Success($"Роль {existingRole.Name} видалено");
                }
                else 
                    _notify.Error($"Роль {existingRole.Name} використовується");
            }
            else
                _notify.Error($"Роль {existingRole.Name} не може бути видаленою");

            var roles = await _roleManager.Roles.ToListAsync();
            var mappedRoles = _mapper.Map<IEnumerable<RoleViewModel>>(roles);
            var html = await _viewRenderer.RenderViewToStringAsync("_ViewAll", mappedRoles);
            
            return new JsonResult(new { isValid = true, html = html });
        }
    }
}

WebUI/Areas/Admin/Views/Role/Index.cshtml
@{
	ViewData["Title"] = "Ролі";
	ViewData["Caption"] = "Керування Ролями";
}

<div class="card">
	<div class="col-sm-12" style="padding:20px">
		<a onclick="jQueryModalGet('/admin/role/OnGetCreateOrEdit','Створити Роль')" class="btn bg-success mr-2">
			<i class="fa fa-plus-square"></i> Створити
		</a>
		<a id="reload" class="btn btn-primary text-white">
			<i class="fa fas fa-bolt"></i>
			Перезавантижити
		</a>
	</div>
	<div id="viewAll" class="card-body table-responsive">
	</div>
</div>

@section Scripts
{
	<script src="~/js/site.js"></script>
	<script>
		$(document).ready(function () {
			$("#roleTable").DataTable({
				language: {
					url: "//cdn.datatables.net/plug-ins/1.10.18/i18n/Ukrainian.json"
				},
			});
			loadData();
			$('#reload').on('click', function () {
				loadData();
			});
		});
		function loadData() {
			$('#viewAll').load('/admin/role/LoadAll');
		}
	</script>
}

WebUI/Areas/Admin/Views/Role/_Create.cshtml
@using WebUI.Areas.Admin.Models
@model RoleViewModel

<form id="create-form" method="post" asp-area="Admin" asp-controller="Role" asp-route-id="@Model.Id" asp-action="OnPostCreate" onsubmit="return jQueryModalPost(this);">
	<div class="form-group row">
		<label class="col-md-3 col-form-label">Ім'я</label>
		<div class="col-md-9">
			<input type="text" asp-for="Name" name="Name" class="form-control">
			<span asp-validation-for="Name" class="text-danger"></span>
		</div>
	</div>
	<div class="form-group justify-content-between" style="margin-bottom: 0px !important">
		<button type="submit" class="btn btn-success mr-2">
			<span class="icon text-white-50">
				<i class="fas fa-check"></i>
			</span>
			Зберегти
		</button>
		<button type="submit" class="btn btn-default close-button" data-dismiss="modal">
			<span class="icon text-dark-50" style="opacity: 50%">
				<i class="fas fa-times"></i>
			</span>
			Відмінити
		</button>
	</div>
</form>

<script type="text/javascript" language=javascript>
	$.validator.unobtrusive.parse(document);
</script>

WebUI/Areas/Admin/Views/Role/_ViewAll.cshtml
@using WebUI.Areas.Admin.Models
@using Application.Enums

@model IEnumerable<RoleViewModel>

<table class="table table-striped" id="roleTable">
	<thead>
		<tr>
			<th>
				Роль
			</th>
			<th>
				ІД
			</th>
			<th style="width:10%">
				Дії
			</th>
		</tr>
	</thead>
	<tbody>
		@foreach (var role in Model)
		{
			<tr>
				<td>
					@role.Name
				</td>
				<td>
					@role.Id
				</td>
				<td class="text-right">
					<div class="btn-group">
						@if (role.Name != Roles.SuperAdmin.ToString())
						{
							<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								Дії
							</button>

							<div class="dropdown-menu shadow animated--grow-in">
								<a onclick="jQueryModalGet('/admin/role/OnGetCreateOrEdit?id=@role.Id','Редагувати Роль')" class="dropdown-item">
									<i class="fas fa-pencil-alt"></i> Редагувати
								</a>
								<form id="form_delete_@role.Id" asp-controller="Role" method="post" asp-action="OnPostDelete" asp-route-id="@role.Id" onsubmit="return jQueryModalDelete(this)" class="d-inline">
									<a href="javascript:$('#form_delete_@role.Id').submit();" class="dropdown-item"><i class="fas fa-trash-alt"></i> Видалити</a>
								</form>

								<a style='margin-right:16px' asp-controller="Permission" asp-action="Index" asp-route-roleId="@role.Id" class="dropdown-item">
									<i class="fas fa-wrench"></i> Керувати Дозволами
								</a>
							</div>
						}
					</div>
				</td>
			</tr>
		}
	</tbody>
</table>

<script>
	$(document).ready(function () {
		$("#roleTable").DataTable({
			language: {
				url: "//cdn.datatables.net/plug-ins/1.10.18/i18n/Ukrainian.json"
			},
		});
	});
</script>