WebUI/Areas/Entities/Models/DistrictViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace WebUI.Areas.Entities.Models
{
	public class DistrictViewModel
	{
		[Display(Name = "ІД")]
		public int Id { get; set; }

		[Display(Name = "Назва")]
		public string Name { get; set; }
	}
}

WebUI/Areas/Entities/Controllers/DistrictController.cs
using AdminPanel.Application.Features.Communities.Commands;
using AdminPanel.Application.Features.Communities.Queries.GetAllCached;
using AdminPanel.Application.Features.Communities.Queries.GetById;
using AdminPanel.Web.Abstractions;
using WebUI.Areas.Entities.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;

namespace WebUI.Areas.Entities.Controllers
{
    [Area("Entities")]
    public class DistrictController : BaseController<DistrictController>
	{
        // GET: DistrictController
        public IActionResult Index()
        {
            var model = new DistrictViewModel();
            return View(model);
        }

        public async Task<IActionResult> LoadAll()
        {
            var response = await _mediator.Send(new GetAllDistrictsCachedQuery());
            if (response.Succeeded)
            {
                var viewModel = _mapper.Map<List<DistrictViewModel>>(response.Data);
                return PartialView("_ViewAll", viewModel);
            }
            return null;
        }

        public async Task<JsonResult> OnGetCreateOrEdit(int id = 0)
        {
            if (id == 0)
            {
                var districtViewModel = new DistrictViewModel();
                return new JsonResult(new { isValid = true, html = await _viewRenderer.RenderViewToStringAsync("_CreateOrEdit", districtViewModel) });
            }
            else
            {
                var response = await _mediator.Send(new GetDistrictByIdQuery() { Id = id });
                if (response.Succeeded)
                {
                    var districtViewModel = _mapper.Map<DistrictViewModel>(response.Data);
                    return new JsonResult(new { isValid = true, html = await _viewRenderer.RenderViewToStringAsync("_CreateOrEdit", districtViewModel) });
                }
                return null;
            }
        }

        [HttpPost]
        public async Task<JsonResult> OnPostCreateOrEdit(int id, DistrictViewModel district)
        {
            if (ModelState.IsValid)
            {
                if (id == 0)
                {
                    var createDistrictCommand = _mapper.Map<CreateDistrictCommand>(district);
                    var result = await _mediator.Send(createDistrictCommand);

                    if (result.Succeeded)
                    {
                        id = result.Data;
                        _notify.Success($"Район {district.Name} створений");
                    }
                    else
                        _notify.Error("Помилка створення");
                }
                else
                {
                    var updateDistrictCommand = _mapper.Map<UpdateDistrictCommand>(district);
                    var result = await _mediator.Send(updateDistrictCommand);
                    if (result.Succeeded) _notify.Success($"Район {district.Name} змінений");
                }
                
                var response = await _mediator.Send(new GetAllDistrictsCachedQuery());
                
                if (response.Succeeded)
                {
                    var viewModel = _mapper.Map<List<DistrictViewModel>>(response.Data);
                    var html = await _viewRenderer.RenderViewToStringAsync("_ViewAll", viewModel);
                    return new JsonResult(new { isValid = true, html = html });
                }
                else
                {
                    _notify.Error("Помилка створення");
                    return null;
                }
            }
            else
            {
                
                
                var html = await _viewRenderer.RenderViewToStringAsync("_CreateOrEdit", district);
                return new JsonResult(new { isValid = false, html = html });
            }
        }

        [HttpPost]
        public async Task<JsonResult> OnPostDelete(int id)
        {
            var byIdResponse = await _mediator.Send(new GetDistrictByIdQuery() { Id = id });
            var district = _mapper.Map<DistrictViewModel>(byIdResponse.Data);

            var deleteCommand = await _mediator.Send(new DeleteDistrictCommand { Id = id });
            
            if (deleteCommand.Succeeded)
            {
                _notify.Success($"Район {district.Name} видалений");
                var response = await _mediator.Send(new GetAllDistrictsCachedQuery());
                
                if (response.Succeeded)
                {
                    var viewModel = _mapper.Map<List<DistrictViewModel>>(response.Data);
                    var html = await _viewRenderer.RenderViewToStringAsync("_ViewAll", viewModel);
                    return new JsonResult(new { isValid = true, html = html });
                }
                else
                {
                    _notify.Error("Помилка видалення");
                    return null;
                }
            }
            else
            {
                _notify.Error("Помилка видалення");
                return null;
            }
        }
    }
}

WebUI/Areas/Entities/Views/District/Index.cshtml
@{
	ViewData["Title"] = "Райони";
	ViewData["Caption"] = "Редагування районів";
}

@using WebUI.Areas.Entities.Models
@using AdminPanel.Application.Constants
@model DistrictViewModel

@{ 
	bool view = AuthorizationService.AuthorizeAsync(User, Permissions.Districts.View).Result.Succeeded;
}

@if (view)
{
    <div class="card">
        <div class="col-sm-12" style="padding:20px">

            @if ((AuthorizationService.AuthorizeAsync(User, Permissions.Districts.Create)).Result.Succeeded)
            {
                <a onclick="jQueryModalGet('/entities/district/OnGetCreateOrEdit','Створити район')" class="btn bg-success mr-2">
                    <i class="fa fa-plus-square"></i> Створити
                </a>
            }

            <a id="reload" class="btn btn-primary text-white">
                <i class="fa fas fa-bolt"></i>
                Перевантажити
            </a>
        </div>

        @if (view)
        {
            <div id="viewAll" class="card-body table-responsive">
            </div>
        }
    </div>
}
else 
{
    <h2 class="text-center">Не доступно для вас</h2>
}

@section Scripts
{
    <script src="~/js/site.js"></script>
    <script>
        $(document).ready(function () {
			$("#districtTable").DataTable({
				language: {
					url: "//cdn.datatables.net/plug-ins/1.10.18/i18n/Ukrainian.json"
				},
			});
            loadData();
            $('#reload').on('click', function () {
                loadData();
            });
        });
        function loadData() {
			$('#viewAll').load('/entities/district/LoadAll');
        }
    </script>
}

WebUI/Areas/Entities/Views/District/_CreateOrEdit.cshtml
@using WebUI.Areas.Entities.Models
@model DistrictViewModel
@using AdminPanel.Application.Constants

@*@if (AuthorizationService.AuthorizeAsync(User, Permissions.Communities.Edit).Result.Succeeded || AuthorizationService.AuthorizeAsync(User, Permissions.Communities.Create).Result.Succeeded)
	{*@
<form id="create-form" method="post" asp-controller="District" asp-action="OnPostCreateOrEdit" asp-route-id="@Model.Id" onsubmit="return jQueryModalPost(this);" enctype="multipart/form-data">
	<div class="row">
		<div class="col-md-12">
			<div class="form-group row">
				<label class="col-md-3 col-form-label">Ім'я району</label>
				<div class="col-md-9">
					<input type="text" asp-for="Name" name="Name" class="form-control">
					<span asp-validation-for="Name" class="text-danger"></span>
				</div>
			</div>
			<div class="form-group row">
				<div class="col-md-3">
				</div>
			</div>
		</div>
	</div>
	<div class="form-group justify-content-between" style="margin-bottom: 0px !important">
		<button type="submit" class="btn btn-success">Зберегти</button>
		<button type="submit" class="btn btn-default close-button" data-dismiss="modal">Відмінити</button>
	</div>
</form>

<script type="text/javascript" language=javascript>
	$.validator.unobtrusive.parse(document);
</script>
@*}*@

WebUI/Areas/Entities/Views/District/_ViewAll.cshtml
@using WebUI.Areas.Entities.Models
@using AdminPanel.Application.Constants

@model IEnumerable<DistrictViewModel>

@{
	bool delete = AuthorizationService.AuthorizeAsync(User, Permissions.Districts.Delete).Result.Succeeded;
	bool edit = AuthorizationService.AuthorizeAsync(User, Permissions.Districts.Edit).Result.Succeeded;
}

@if (AuthorizationService.AuthorizeAsync(User, Permissions.Districts.View).Result.Succeeded)
{
	<style>
		#districtTable > tr > th {
			border-top-width: 0
		}
	</style>
	<table id="districtTable" class="table table-striped" width="100%" cellspacing="0">
		<thead>
			<tr >
				<th>ІД</th>
				<th>Ім'я</th>
				@if (delete || edit)
				{
					<th>Дії</th>
				}
			</tr>
		</thead>
		<tbody>
			@foreach (var district in Model)
			{
				<tr>
					<td>
						@district.Id
					</td>
					<td>
						@district.Name Район
					</td>
					@if (delete || edit)
					{
						<td text-right">
							<div class="btn-group">
								<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
									Дії
								</button>
								<div class="dropdown-menu shadow animated--grow-in">
									@if (edit)
									{
										<a onclick="jQueryModalGet('/entities/district/OnGetCreateOrEdit?id=@district.Id','Редагування району')" class="dropdown-item"><i class="fas fa-pencil-alt"></i>  Редагувати</a>
									}
									@if (delete)
									{
										<form id="form_delete_@district.Id" asp-area="Entities" asp-controller="District" method="post" asp-action="OnPostDelete" asp-route-id="@district.Id" onsubmit="return jQueryModalDelete(this)">
											<a href="javascript:$('#form_delete_@district.Id').submit();" class="dropdown-item"><i class="fas fa-trash-alt"></i>  Видалити</a>
										</form>
									}
								</div>
							</div>
						</td>
					}
				</tr>
			}
		</tbody>
	</table>
}
<script>
	$(document).ready(function () {
		$("#districtTable").DataTable({
			language: {
				url: "//cdn.datatables.net/plug-ins/1.10.18/i18n/Ukrainian.json"
			},
		});;
	});
</script>