WebUI/Areas/Admin/Models/UserViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using WebUI.Areas.Entities.Models;

namespace WebUI.Areas.Admin.Models
{
	public class UserViewModel
    {
        public string Id { get; set; }

        public string UserName { get; set; }

        public string FirstName { get; set; }

        public string MiddleName { get; set; }

        public string LastName { get; set; }

        public string ProfilePicture { get; set; }

        public int СommunityId { get; set; }

        public string Email { get; set; }
        
        public bool IsActive { get; set; } = true;
        
        public string Password { get; set; }
        
        public string ConfirmPassword { get; set; }
        
        public bool EmailConfirmed { get; set; }

        public string PhoneNumber { get; set; }
        
        public int CommunityId { get; set; }

        public string Description { get; set; }
        
        public CommunityViewModel Community { get; set; }

        public SelectList Communities { get; set; }
    }
}

WebUI/Areas/Admin/Controllers/ProfileController.cs
using Application.Features.Communities.Queries.GetAllCached;
using Infrastructure.AuditModels;
using WebUI.Abstractions;
using Application.Features.Logs.Commands;
using Infrastructure.Identity.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using WebUI.Areas.Admin.Models;
using WebUI.Areas.Entities.Models;
using WebUI.Services;
using System.Linq;
using Application.Features.Communities.Commands;

namespace WebUI.Areas.Admin
{
	[Area("Admin")]
	public class ProfileController : BaseUserController<ProfileController>
	{
		private readonly UserManager<ApplicationUser> _userManager;
		private readonly IWebHostEnvironment _webHostEnvironment;

		public ProfileController(UserManager<ApplicationUser> userManager,
			IWebHostEnvironment webHostEnvironment)
		{
			_userManager = userManager;
			_webHostEnvironment = webHostEnvironment;

			ImageService.RootPass = _webHostEnvironment.WebRootPath;
		}

		public async Task<IActionResult> Index(string id)
		{
			UserViewModel user = _mapper.Map<UserViewModel>(await GetCurrentUser(id));
			var response = await _mediator.Send(new GeUserCommunitiesQuery() { UserId = user.Id });

			if (response.Succeeded)
				user.Communities = _mapper.Map<List<CommunityViewModel>>(response.Data);
			else
				_notify.Error($"Помилка при завантажені громад користувача");

			return View(user);
		}

		public async Task<IActionResult> Edit(string id)
		{
			UserViewModel user = _mapper.Map<UserViewModel>(await GetCurrentUser(id));
			var response = await _mediator.Send(new GeUserCommunitiesQuery() { UserId = user.Id });

			if (response.Succeeded)
			{
				var responseFree = await _mediator.Send(new GetFreeCommunitiesQuery());
				if (responseFree.Succeeded)
				{
					var freeData = _mapper.Map<IEnumerable<CommunityViewModel>>(responseFree.Data).ToList();
					var data = _mapper.Map<IEnumerable<CommunityViewModel>>(response.Data);
					freeData.AddRange(data);
					user.CommunitiesSelected = data.Select(c => c.Id).ToList();

					user.CommunitiesList = new SelectList(freeData.OrderBy(x => x.District.Name).ThenBy(x => x.Name),
						nameof(CommunityViewModel.Id), nameof(CommunityViewModel.Name),
						null, "District.Name");
				}
				return View(user);
			}

			_notify.Error("Помилка завантаження громад");
			return null;
		}

		[HttpPost]
		public async Task<IActionResult> Edit(UserViewModel user)
		{
			if (ModelState.IsValid)
			{
				ApplicationUser appUser = await GetCurrentUser(user.Id);

				Log log = new Log()
				{
					UserId = _userService.UserId,
					Action = "Update",
					TableName = "Users",
					Key = appUser.Id,
					OldValues = new AuditUserModel(_mapper.Map<UserViewModel>(appUser)),
					NewValues = new AuditUserModel(user)
				};

				appUser.Description = user.Description;
				appUser.Chat = user.Chat;
				appUser.FirstName = user.FirstName;
				appUser.MiddleName = user.MiddleName;
				appUser.LastName = user.LastName;

				var response = await _mediator.Send(new GeUserCommunitiesQuery() { UserId = user.Id });
				if (response.Succeeded)
				{
					if (user.CommunitiesSelected != null)
					{
						var currentCommunitiesIds = response.Data.Select(c => c.Id);

						var newCommunities = user.CommunitiesSelected.Except(currentCommunitiesIds);
						var delCommunities = currentCommunitiesIds.Except(user.CommunitiesSelected);
						await ExecuteUpdateCommands(GenerateUpdate(newCommunities, user.Id));
						await ExecuteUpdateCommands(GenerateUpdate(delCommunities, null));
					}
					else
					{
						var delAll = response.Data.Select(c => new UpdateCommunityCommand()
						{
							Id = c.Id,
							ApplicationUserId = null
						});
						await ExecuteUpdateCommands(delAll);
					}
				}

				try
				{
					await _userManager.UpdateAsync(appUser);

					if (user.PhoneNumber != appUser.PhoneNumber)
						await _userManager.SetPhoneNumberAsync(appUser, user.PhoneNumber);

					if (user.Email.ToLower() != appUser.Email.ToLower())
					{
						await _userManager.SetEmailAsync(appUser, user.Email);
						appUser.EmailConfirmed = true;
						await _userManager.UpdateAsync(appUser);
					}

					_notify.Success($"Користувач {user.UserName} був успішно змінений");

					await _mediator.Send(new AddLogCommand() { Log = log });
					return RedirectToAction(nameof(Index), new { Id = user.Id });
				}
				catch (Exception ex)
				{
					_notify.Error(ex.Message);
				}
			}

			var freeData = await GetAllFreeData(user.Id);

			user.CommunitiesList = new SelectList(freeData.OrderBy(x => x.District.Name).ThenBy(x => x.Name),
				nameof(CommunityViewModel.Id), nameof(CommunityViewModel.Name),
				null, "District.Name");

			return View(user);
		}

		public async Task<IActionResult> DeleteImage(string id)
		{
			ApplicationUser appUser = await GetCurrentUser(id);

			if (appUser != null && appUser.ProfilePicture != null)
			{
				if (ImageService.DeleteImageLocal(appUser.ProfilePicture))
				{
					appUser.ProfilePicture = null;

					if ((await _userManager.UpdateAsync(appUser)).Succeeded)
						_notify.Success($"Фото профілю успішно змінено");
					else
						_notify.Error($"Помилка при видалені фото");
				}
			}
			return RedirectToAction(nameof(Edit), new { Id = id });
		}

		public async Task<IActionResult> ChangeProfileImage(string id)
		{
			return new JsonResult(new
			{
				isValid = true,
				html = await _viewRenderer.RenderViewToStringAsync("_ChangeImage", id)
			});
		}

		[HttpPost]
		public async Task<IActionResult> ChangeProfileImage(string id, string fileName, IFormFile blob)
		{
			try
			{
				ApplicationUser appUser = await GetCurrentUser(id);

				if (appUser != null)
				{
					string imagePath = ImageService.SaveImageLocal(blob, Path.GetExtension(fileName));
					if (!String.IsNullOrEmpty(imagePath))
					{
						string oldImage = appUser.ProfilePicture;
						appUser.ProfilePicture = imagePath;
						if ((await _userManager.UpdateAsync(appUser)).Succeeded)
						{
							ImageService.DeleteImageLocal(oldImage);
							_notify.Success($"Фото профілю успішно змінено");
						}
						else
							ImageService.DeleteImageLocal(imagePath);
					}
				}
				return new JsonResult(new { isValid = true });
			}
			catch (Exception)
			{
				return new JsonResult(new { isValid = false });
			}
		}

		private async Task<ApplicationUser> GetCurrentUser(string userId)
		{
			if (String.IsNullOrEmpty(userId))
				return await _userManager.GetUserAsync(User);
			return await _userManager.FindByIdAsync(userId);
		}

		private async Task<IEnumerable<CommunityViewModel>> GetAllFreeData(string userId)
		{
			var response = await _mediator.Send(new GeUserCommunitiesQuery() { UserId = userId });

			if (response.Succeeded)
			{
				var responseFree = await _mediator.Send(new GetFreeCommunitiesQuery());
				if (responseFree.Succeeded)
				{
					var freeData = _mapper.Map<IEnumerable<CommunityViewModel>>(responseFree.Data).ToList();
					var data = _mapper.Map<IEnumerable<CommunityViewModel>>(response.Data);
					freeData.AddRange(data);
					return freeData;
				}
			}
			return new List<CommunityViewModel>();
		}
	}
}

WebUI/Areas/Admin/Controllers/UserController.cs
using Application.Enums;
using Application.Features.Communities.Queries.GetAllCached;
using WebUI.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Threading.Tasks;
using WebUI.Areas.Admin.Models;
using WebUI.Areas.Entities.Models;
using WebUI.Services;
using Infrastructure.AuditModels;
using Application.Features.Logs.Commands;
using Infrastructure.Identity.Models;
using System.IO;
using System;

namespace WebUI.Areas.Admin
{
	[Area("Admin")]
	public class UserController : BaseUserController<UserController>
	{
		#region Fields

		private readonly UserManager<ApplicationUser> _userManager;

		private readonly IWebHostEnvironment _webHostEnvironment;

		public object ApplicationUser { get; private set; }

		#endregion

		public UserController(UserManager<ApplicationUser> userManager,
			IWebHostEnvironment webHostEnvironment)
		{
			_userManager = userManager;
			_webHostEnvironment = webHostEnvironment;

			ImageService.RootPass = _webHostEnvironment.WebRootPath;
		}

		#region Main Controller Methods

		public IActionResult Index()
		{
			return View();
		}

		public async Task<IActionResult> LoadAll()
		{
			return PartialView("_ViewAll", await GetUsersExceptCurrentAsync());
		}

		[Authorize(Roles = "SuperAdmin")]
		public async Task<IActionResult> OnGetCreate()
		{
			var response = await _mediator.Send(new GetFreeCommunitiesQuery());

			if (response.Succeeded)
			{
				if (response.Data.Count == 0)
					_notify.Warning("Немає вільних громад");

				var data = _mapper.Map<IEnumerable<CommunityViewModel>>(response.Data);

				var freeCommunities = new SelectList(data.OrderBy(x => x.District.Name).ThenBy(x => x.Name),
					nameof(CommunityViewModel.Id), nameof(CommunityViewModel.Name), null, "District.Name");

				return new JsonResult(new
				{
					isValid = true,
					html = await _viewRenderer.RenderViewToStringAsync("_Create",
					new UserViewModel() { CommunitiesList = freeCommunities }, TempData)
				});
			}

			_notify.Error("Помилка завантаження громад");
			return null;
		}

		[HttpPost]
		[Authorize(Roles = "SuperAdmin")]
		public async Task<IActionResult> OnPostCreate(UserViewModel userModel, string fileName, IFormFile blob)
		{
			if (ModelState.IsValid && !String.IsNullOrEmpty(fileName) && blob != null)
			{
				string imagePath;
				userModel.Password ??= "1";

				try
				{
					imagePath = ImageService.SaveImageLocal(blob, Path.GetExtension(fileName));
				}
				catch (Exception)
				{
					return await FileUploadError(userModel);
				}

				if (String.IsNullOrEmpty(imagePath))
					return await FileUploadError(userModel);

				MailAddress address = new MailAddress(userModel.Email);
				string userName = address.User;
				var user = new ApplicationUser
				{
					Email = userModel.Email,
					UserName = userModel.Email,
					FirstName = userModel.FirstName,
					MiddleName = userModel.MiddleName,
					LastName = userModel.LastName,
					PhoneNumber = userModel.PhoneNumber,
					Chat = userModel.Chat,
					ProfilePicture = imagePath,
					EmailConfirmed = true,
					IsActive = true,
					Description = userModel.Description
				};

				var result = await _userManager.CreateAsync(user, userModel.Password);

				if (result.Succeeded)
				{
					_notify.Success($"Аккаунт {user.Email} створено");

					await _userManager.AddToRoleAsync(user, Roles.Worker.ToString());
					await ExecuteUpdateCommands(GenerateUpdate(userModel.CommunitiesSelected, user.Id));

					Log log = new Log()
					{
						Action = "Create",
						UserId = _userService.UserId,
						TableName = "Users",
						NewValues = new AuditUserModel(userModel),
						Key = user.Id
					};

					await _mediator.Send(new AddLogCommand() { Log = log });

					var htmlData = await _viewRenderer.RenderViewToStringAsync("_ViewAll", await GetUsersExceptCurrentAsync(), TempData);
					return new JsonResult(new { isValid = true, html = htmlData });
				}

				foreach (var error in result.Errors)
					_notify.Error(error.Description);

				ImageService.DeleteImageLocal(imagePath);
			}

			_notify.Success($"Фото профілю не вибрано");

			var html = await _viewRenderer.RenderViewToStringAsync("_Create", userModel, TempData);
			return new JsonResult(new { isValid = false, html = html });
		}

		[HttpPost]
		[Authorize(Roles = "SuperAdmin")]
		public async Task<JsonResult> OnPostDelete(string id)
		{
			var user = await _userManager.FindByIdAsync(id);

			if (user == null)
				_notify.Error($"Користувача не знайдено");
			else if (user.FirstName != "Super" && user.FirstName != "Default")
			{
				if (ImageService.DeleteImageLocal(user.ProfilePicture))
				{
					var response = await _mediator.Send(new GeUserCommunitiesQuery() { UserId = user.Id });

					if (response.Succeeded)
					{
						await ExecuteUpdateCommands(GenerateUpdate(response.Data.Select(c => c.Id), null));
					}
					else
					{
						_notify.Error($"Помилка при отримані громад працівника");
						var htmlData = await _viewRenderer.RenderViewToStringAsync("_ViewAll", await GetUsersExceptCurrentAsync());
						return new JsonResult(new { isValid = true, html = htmlData });
					}
					
					var result = await _userManager.DeleteAsync(user);

					if (result.Succeeded)
					{
						_notify.Success($"Користувач {user.FirstName + " " + user.LastName} був успішно видалений");

						Log log = new Log()
						{
							Action = "Delete",
							UserId = _userService.UserId,
							TableName = "Users",
							OldValues = new AuditUserModel(_mapper.Map<UserViewModel>(user)),
							Key = user.Id
						};

						await _mediator.Send(new AddLogCommand() { Log = log });
					}
					else
						_notify.Error($"Помилка при видалені користувача");
				}
				else
					_notify.Error($"Помилка при видалені фото профілю з сервера.");
			}
			else
				_notify.Error($"Не можна видалити базових користувачів");

			var html = await _viewRenderer.RenderViewToStringAsync("_ViewAll", await GetUsersExceptCurrentAsync());
			return new JsonResult(new { isValid = true, html = html });
		}

		[HttpPost]
		[Authorize(Roles = "SuperAdmin")]
		public async Task<JsonResult> OnPostDeactivate(string id)
		{
			var user = await _userManager.FindByIdAsync(id);

			if (user == null)
				_notify.Error($"Користувача не знайдено");
			else if (user.FirstName != "Super" && user.FirstName != "Default")
			{
				user.IsActive = !user.IsActive;
				var result = await _userManager.UpdateAsync(user);

				if (result.Succeeded)
				{
					_notify.Success($"Користувач {user.FirstName + " " + user.LastName} " +
					(user.IsActive ? "активований" : "деактивований"));

					Log log = new Log()
					{
						UserId = _userService.UserId,
						Key = user.Id,
						TableName = "Users",
						NewValues = new AuditUserModel(_mapper.Map<UserViewModel>(user)),
						Action = user.IsActive ? "Activated" : "Deactivated"
					};

					await _mediator.Send(new AddLogCommand() { Log = log });
				}
				else
					_notify.Error($"Помилка збереження змін.");
			}
			else
				_notify.Error($"Не можна деактивувати базових користувачів");

			var html = await _viewRenderer.RenderViewToStringAsync("_ViewAll", await GetUsersExceptCurrentAsync());
			return new JsonResult(new { isValid = true, html = html });
		}

		#endregion

		#region Other Methods
		private async Task<JsonResult> FileUploadError(UserViewModel userModel)
		{
			_notify.Error("Помилка про завантаженні фото профілю");
			return new JsonResult(new
			{
				isValid = false,
				html = await _viewRenderer.RenderViewToStringAsync("_Create", userModel)
			});
		}

		private async Task<IEnumerable<UserViewModel>> GetUsersExceptCurrentAsync()
		{
			var currentUser = await _userManager.GetUserAsync(HttpContext.User);
			var allUsersExceptCurrentUser = await _userManager.Users.Where(a => a.Id != currentUser.Id).ToListAsync();
			return _mapper.Map<IEnumerable<UserViewModel>>(allUsersExceptCurrentUser);
		}
		#endregion
	}
}

WebUI/Areas/Admin/Views/User/Index.cshtml
@{ ViewData["Title"] = "Користувачі";
	ViewData["Caption"] = "Редагувати користувачів";
}

@using AdminPanel.Application.Constants

@if ((AuthorizationService.AuthorizeAsync(User, Permissions.Users.View)).Result.Succeeded)
{
	<div class="card">
		<div class="col-sm-12" style="padding:20px">
			@if ((AuthorizationService.AuthorizeAsync(User, Permissions.Users.Create)).Result.Succeeded)
			{
				<a onclick="jQueryModalGet('/admin/user/OnGetCreate','Сторити Працівника')" class="btn bg-success mr-2">
					<i class="fa fa-plus-square"></i> Створити
				</a>
			}
			<a id="reload" class="btn btn-primary text-white">
				<i class="fa fas fa-bolt"></i>
				Перевантажити
			</a>
		</div>
		<div id="viewAll" class="card-body table-responsive">
		</div>
	</div>
}
else
{
	<h2 class="text-center">Не доступно для вас</h2>
}

@section Scripts
{
	<script src="~/js/site.js"></script>
	<script>
		$(document).ready(function () {
			$("#userTable").DataTable({
				language: {
					url: "//cdn.datatables.net/plug-ins/1.10.18/i18n/Ukrainian.json"
				},
			});
			loadData();
			$('#reload').on('click', function () {
				loadData();
			});
		});
		function loadData() {
			$('#viewAll').load('/admin/user/LoadAll');
		}
	</script>
}

WebUI/Areas/Admin/Views/User/_ViewAll.cshtml
@using WebUI.Areas.Admin.Models
@using WebUI
@model IEnumerable<UserViewModel>
@using AdminPanel.Application.Constants
@using System.IO
@using WebUI.Services

@if ((AuthorizationService.AuthorizeAsync(User, Permissions.Users.View)).Result.Succeeded) 
{
<table class="table table-striped" id="userTable">
    <thead>
        <tr>
            <th>
                Працівник
            </th>
            <th>
                Пошта
            </th>
            <th>
                Статус
            </th>
            <th style="width:10%">
                Дії
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model)
        {
            <tr>
                <td>
                    <div class="row">
                        @if (user.ProfilePicture != null)
                        {
                            <div class="col-sm" style=" max-width: 80px;margin-right: 20px;">
                                <img class="img-profile rounded-circle" style="height: 75px; width:75px; object-fit: cover;" src="@ENV.ImagePath@user.ProfilePicture"
                                     onerror="this.onerror = null; this.src = '@Url.Content("~/images/users/default-user.png")';">
                            </div>
                        }
                        else
                        {
                            <div class="col-sm" style="max-width:80px; margin-right: 20px;">
                                <img class="img-profile rounded-circle" style="height: 75px;width:75px;object-fit: cover;" src="~/images/users/default-user.png">
                            </div>
                        }
                        <div class="col-sm">
                            <a>
                                @user.FirstName @user.LastName
                            </a>
                            <br>
                            <small>
                                @user.Id
                            </small>
                        </div>
                    </div>
                </td>
                <td>
                    <a>
                        @user.Email
                    </a>
                    <br>
                    <small>
                        @if (user.EmailConfirmed)
                        {
                            <span class="badge badge-success">Підтверджено</span>
                        }
                        else
                        {
                            <span class="badge badge-danger">Не підтверджено</span>
                        }
                    </small>
                </td>
                <td>
                    @if (user.IsActive)
                    {
                        <span class="badge badge-success">Активний</span>
                    }
                    else
                    {
                        <span class="badge badge-danger">Деактивований</span>
                    }
                </td>
                <td>
                    <div class="btn-group">
                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Дії
                        </button>
                        <div class="dropdown-menu shadow animated--grow-in">
                            <a style='margin-right:16px' asp-area="Admin" asp-controller="Profile" asp-action="Index" asp-route-id="@user.Id" class="dropdown-item">
                                <i class="fas fa-user"></i> Профіль
                            </a>
                            <a style='margin-right:16px' asp-area="Admin" asp-controller="Chat" asp-action="Index" asp-route-id="@user.Id" class="dropdown-item">
								<i class="fas fa-comments"></i> Чати
							</a>
                            @if (User.IsInRole("SuperAdmin"))
                            {
                                <a style='margin-right:16px' asp-controller="UserRole" asp-action="Index" asp-route-userId="@user.Id" class="dropdown-item">
                                    <i class="fas fa-wrench"></i> Керування Ролями
                                </a>
                                <a class="dropdown-item" asp-area="Identity" asp-page="/Account/AuditLog" asp-route-id="@user.Id">
                                    <i class="fas fa-list"></i> Історія
                                </a>
                                <form id="form_delete_@user.Id" asp-controller="User" method="post" asp-action="OnPostDelete" asp-route-id="@user.Id" onsubmit="return jQueryModalDelete(this)" class="d-inline">
                                    <a href="javascript:$('#form_delete_@user.Id').submit();" class="dropdown-item"><i class="fas fa-trash-alt"></i> Видалити</a>
                                </form>
                                <form id="form_deactivate_@user.Id" asp-controller="User" method="post" asp-action="OnPostDeactivate" asp-route-id="@user.Id" onsubmit="return jQueryModalDeactivate(this)" class="d-inline">
                                    @if (user.IsActive)
                                    {
                                        <a href="javascript:$('#form_deactivate_@user.Id').submit();" class="dropdown-item"><i class="fas fa-key"></i> Деактивувати</a>
                                    }
                                    else
                                    {
                                        <a href="javascript:$('#form_deactivate_@user.Id').submit();" class="dropdown-item"><i class="fas fa-key"></i> Активувати</a>
                                    }
                                </form>
                            }
                        </div>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>
}

<script>
    $(document).ready(function () {
        $("#userTable").DataTable({
            language: {
                url: "//cdn.datatables.net/plug-ins/1.10.18/i18n/Ukrainian.json"
            },
        });
    });
</script>